### ISSUE TITLE
functions.mosshe - don't exit if mail not found, maybe we just want to monitor silently :)

### ISSUE THREAD

**Issue by JayGoldberg** [wyae/MoSShE#6]
in line around:
```
if [ -z `which mail` ]; then
    	echo "MoSShE: 'mail' command not availabe, cannot send alerts!"
	logger -t MoSShE -p local0.alert "MoSShE: 'mail' command not availabe, cannot send alerts!"
```

also the checking command could be:
`if which mail &>/dev/null; then` or `if [ $(which mail) ]; then`

`[` aka `test` is a shell builtin on BusyBox v1.23.2 `ash` anyway, so no resources saved really, so the second is cleaner.

**Comment by wyae** [comment]
closed by 16.6.12
