### ISSUE TITLE
html templates moved to www/ but script later deletes them

### ISSUE THREAD

**Issue by JayGoldberg** [wyae/MoSShE#9]
In 363cd6477c4c0b201fa5837d770a35215e26c3c7 this was done, but:
```
grep -rn rm mosshe/functions.mosshe |grep html
119:    [ "$1" -a "$WWWDIR" ] && rm -f $WWWDIR/*.html
```

So either we can add an extension like `.tpl` to keep them from being deleted, or, I'd prefer to move them back to `$DATADIR` and leave www/ as a straight copy to the user's intended webroot `$WWWDIR` and change `functions.mosshe` lines like `cat $WWWDIR/template_head.html \`  to `cat $DATADIR/template_head.html \`.

**Comment by wyae** [comment]
fixed by v16.6.12
